# Generated by Django 5.2.7 on 2025-11-07 09:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='fish_species',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('tilapia', 'Tilapia'), ('nile perch', 'Nile Perch'), ('trout', 'Trout'), ('catfish', 'Catfish'), ('other', 'Other')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
