# Generated by Django 5.2.7 on 2026-02-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmerprofile',
            options={'ordering': ['-date_registered']},
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='place_of_farming',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Farm size in acres or square meters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farming_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='core.farmingmethod'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='core.fishagegroup'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='core.county'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='fish_species',
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='subcounty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='core.subcounty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('aspiring-farmer', 'Aspiring Farmer'), ('farmer', 'Farmer'), ('fisherman', 'Fisherman'), ('buyer', 'Buyer'), ('seller', 'Seller')], db_index=True, default='farmer', max_length=20),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='fish_species',
            field=models.ManyToManyField(blank=True, related_name='farmers', to='core.fishspecies'),
        ),
    ]
