# Generated by Django 5.2.7 on 2026-02-28 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_farmerprofile_options_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='fish_species',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='fish_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='core.fishspecies'),
        ),
    ]
