# Generated by Django 5.2.7 on 2026-04-18 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeding', '0006_alter_feed_created_at_feedingnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feeding_frequency', models.IntegerField()),
                ('feeding_consistency', models.FloatField()),
                ('avg_protein', models.FloatField()),
                ('temperature', models.FloatField()),
                ('oxygen', models.FloatField()),
                ('ph', models.FloatField()),
                ('stocking_density', models.FloatField()),
                ('current_weight', models.FloatField()),
                ('predicted_weight', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_snapshots', to='feeding.feedingplan')),
            ],
        ),
    ]
