# Generated by Django 5.2.7 on 2026-04-26 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0001_initial'),
        ('farm', '0004_remove_pond_farm_pond_owner_delete_farm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('age_group', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('ph', models.FloatField()),
                ('oxygen', models.FloatField()),
                ('stocking_density', models.FloatField()),
                ('water_source', models.CharField(max_length=50)),
                ('recent_deaths', models.IntegerField()),
                ('death_rate', models.FloatField()),
                ('symptoms', models.JSONField()),
                ('predicted_disease', models.CharField(max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(max_length=50)),
                ('priority_actions', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('prevention', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_logs', to='farm.pond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
