# Generated by Django 5.2.7 on 2026-04-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0002_diseaselog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaselog',
            name='water_source',
        ),
    ]
