# Generated by Django 5.2.7 on 2026-05-27 21:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('guide', 'Guide'), ('module', 'Module')], default='guide', max_length=10)),
                ('module_key', models.CharField(blank=True, help_text='Frontend module identifier (e.g., growth_prediction)', max_length=100, null=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name for frontend UI', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdvisoryGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, help_text='Optional introduction shown at top of guide')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_guides', to='core.fishagegroup')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_guides', to='core.county')),
                ('farming_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_guides', to='core.farmingmethod')),
                ('fish_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_guides', to='core.fishspecies')),
                ('subcounty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_guides', to='core.subcounty')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='advisory.advisorysection')),
            ],
        ),
        migrations.CreateModel(
            name='AdvisoryStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='advisory/steps/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this step is required for onboarding completion')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='advisory.advisoryguide')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedingGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeding_frequency_per_day', models.PositiveIntegerField(help_text='e.g., 2–3 times per day')),
                ('feed_type', models.CharField(max_length=100)),
                ('feeding_percentage_body_weight', models.FloatField(help_text='e.g., 3% of body weight')),
                ('feeding_times', models.JSONField(help_text="Example: ['08:00', '13:00', '17:00']")),
                ('instructions', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fishagegroup')),
                ('farming_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmingmethod')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fishspecies')),
            ],
        ),
        migrations.CreateModel(
            name='FishQualityChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_appearance', models.TextField(help_text='e.g., shiny skin, no wounds')),
                ('behavior', models.TextField(help_text='e.g., active swimming, responsive')),
                ('size_uniformity', models.TextField(help_text='e.g., similar sizes across batch')),
                ('health_indicators', models.TextField(help_text='e.g., no lesions, no discoloration')),
                ('rejection_signs', models.TextField(help_text='Conditions under which fish should NOT be purchased')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checklists', to='core.fishagegroup')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checklists', to='core.fishspecies')),
            ],
        ),
        migrations.CreateModel(
            name='FishSourcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcing_guidelines', models.TextField()),
                ('recommended_sources', models.TextField(help_text='Where to buy (hatcheries, certified farms, etc.)')),
                ('transportation_tips', models.TextField(help_text='How to transport fish safely')),
                ('average_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('average_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_guides', to='core.fishagegroup')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_guides', to='core.county')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_guides', to='core.fishspecies')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='advisory.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockingGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_density', models.CharField(help_text='e.g., 2–4 fish per m²', max_length=100)),
                ('min_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('max_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('water_volume_requirement', models.CharField(blank=True, help_text='e.g., 1000L per 100 fish', max_length=100, null=True)),
                ('acclimatization_procedure', models.TextField()),
                ('stocking_tips', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocking_guidelines', to='core.fishagegroup')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocking_guidelines', to='core.county')),
                ('farming_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocking_guidelines', to='core.farmingmethod')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocking_guidelines', to='core.fishspecies')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('supplier_type', models.CharField(choices=[('hatchery', 'Hatchery'), ('feed_supplier', 'Feed Supplier'), ('equipment_supplier', 'Equipment Supplier')], max_length=50)),
                ('contact_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.county')),
                ('fish_species', models.ManyToManyField(blank=True, related_name='suppliers', to='core.fishspecies')),
                ('subcounty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='core.subcounty')),
            ],
        ),
        migrations.CreateModel(
            name='UserOnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_setup_completed', models.BooleanField(default=False)),
                ('fish_sourcing_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='advisoryguide',
            index=models.Index(fields=['farming_method', 'fish_species', 'age_group'], name='advisory_ad_farming_91ab6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='advisorystep',
            unique_together={('guide', 'step_number')},
        ),
        migrations.AddIndex(
            model_name='fishqualitychecklist',
            index=models.Index(fields=['fish_species', 'age_group'], name='advisory_fi_fish_sp_362272_idx'),
        ),
        migrations.AddIndex(
            model_name='fishsourcing',
            index=models.Index(fields=['county', 'fish_species', 'age_group'], name='advisory_fi_county__bf0ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockingguideline',
            index=models.Index(fields=['fish_species', 'farming_method', 'age_group'], name='advisory_st_fish_sp_6ac989_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['county', 'supplier_type'], name='advisory_su_county__3e8f6a_idx'),
        ),
    ]
