# Generated by Django 5.2.7 on 2026-02-15 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symptoms', models.TextField()),
                ('causes', models.TextField()),
                ('prevention', models.TextField()),
                ('treatment', models.TextField()),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='core.fishspecies')),
            ],
        ),
        migrations.CreateModel(
            name='FishSourcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcing_guidelines', models.TextField()),
                ('average_price_range', models.CharField(blank=True, max_length=100, null=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_guides', to='core.fishagegroup')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_guides', to='core.county')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_guides', to='core.fishspecies')),
            ],
        ),
        migrations.CreateModel(
            name='AdvisoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_procedure', models.TextField()),
                ('feeding_guidelines', models.TextField()),
                ('disease_prevention', models.TextField()),
                ('water_management', models.TextField()),
                ('harvesting_tips', models.TextField()),
                ('sustainability_practices', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='core.fishagegroup')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories', to='core.county')),
                ('farming_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='core.farmingmethod')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='core.fishspecies')),
                ('subcounty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories', to='core.subcounty')),
            ],
            options={
                'verbose_name': 'Advisory Content',
                'verbose_name_plural': 'Advisory Contents',
                'indexes': [models.Index(fields=['farming_method', 'fish_species', 'age_group'], name='advisory_ad_farming_af9187_idx')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('supplier_type', models.CharField(choices=[('hatchery', 'Hatchery'), ('feed_supplier', 'Feed Supplier'), ('equipment_supplier', 'Equipment Supplier')], max_length=50)),
                ('contact_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.county')),
                ('fish_species', models.ManyToManyField(blank=True, related_name='suppliers', to='core.fishspecies')),
                ('subcounty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='core.subcounty')),
            ],
            options={
                'indexes': [models.Index(fields=['county', 'supplier_type'], name='advisory_su_county__3e8f6a_idx')],
            },
        ),
    ]
