# Generated by Django 5.2.7 on 2026-02-19 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name for frontend UI', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='fishdisease',
            name='fish_species',
        ),
        migrations.RemoveField(
            model_name='fishsourcing',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='fishsourcing',
            name='county',
        ),
        migrations.RemoveField(
            model_name='fishsourcing',
            name='fish_species',
        ),
        migrations.CreateModel(
            name='AdvisoryGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, help_text='Optional introduction shown at top of guide')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_guides', to='core.fishagegroup')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_guides', to='core.county')),
                ('farming_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_guides', to='core.farmingmethod')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_guides', to='core.fishspecies')),
                ('subcounty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_guides', to='core.subcounty')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='advisory.advisorysection')),
            ],
        ),
        migrations.CreateModel(
            name='AdvisoryStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='advisory/steps/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this step is required for onboarding completion')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='advisory.advisoryguide')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='UserOnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_setup_completed', models.BooleanField(default=False)),
                ('fish_sourcing_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AdvisoryContent',
        ),
        migrations.DeleteModel(
            name='FishDisease',
        ),
        migrations.DeleteModel(
            name='FishSourcing',
        ),
        migrations.AddIndex(
            model_name='advisoryguide',
            index=models.Index(fields=['farming_method', 'fish_species', 'age_group'], name='advisory_ad_farming_91ab6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='advisorystep',
            unique_together={('guide', 'step_number')},
        ),
    ]
