# Generated by Django 5.2.7 on 2026-02-28 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0002_advisorysection_remove_fishdisease_fish_species_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisoryguide',
            name='fish_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_guides', to='core.fishspecies'),
        ),
    ]
