# Generated by Django 5.2.7 on 2026-03-26 20:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0003_alter_advisoryguide_fish_species'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeding_frequency_per_day', models.PositiveIntegerField(help_text='e.g., 2–3 times per day')),
                ('feed_type', models.CharField(max_length=100)),
                ('feeding_percentage_body_weight', models.FloatField(help_text='e.g., 3% of body weight')),
                ('feeding_times', models.JSONField(help_text="Example: ['08:00', '13:00', '17:00']")),
                ('instructions', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fishagegroup')),
                ('farming_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmingmethod')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fishspecies')),
            ],
        ),
        migrations.CreateModel(
            name='FishQualityChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_appearance', models.TextField(help_text='e.g., shiny skin, no wounds')),
                ('behavior', models.TextField(help_text='e.g., active swimming, responsive')),
                ('size_uniformity', models.TextField(help_text='e.g., similar sizes across batch')),
                ('health_indicators', models.TextField(help_text='e.g., no lesions, no discoloration')),
                ('rejection_signs', models.TextField(help_text='Conditions under which fish should NOT be purchased')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checklists', to='core.fishagegroup')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checklists', to='core.fishspecies')),
            ],
            options={
                'indexes': [models.Index(fields=['fish_species', 'age_group'], name='advisory_fi_fish_sp_362272_idx')],
            },
        ),
        migrations.CreateModel(
            name='FishSourcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcing_guidelines', models.TextField()),
                ('recommended_sources', models.TextField(help_text='Where to buy (hatcheries, certified farms, etc.)')),
                ('transportation_tips', models.TextField(help_text='How to transport fish safely')),
                ('average_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('average_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_guides', to='core.fishagegroup')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_guides', to='core.county')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_guides', to='core.fishspecies')),
            ],
            options={
                'indexes': [models.Index(fields=['county', 'fish_species', 'age_group'], name='advisory_fi_county__bf0ac7_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockingGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_density', models.CharField(help_text='e.g., 2–4 fish per m²', max_length=100)),
                ('min_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('max_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('water_volume_requirement', models.CharField(blank=True, help_text='e.g., 1000L per 100 fish', max_length=100, null=True)),
                ('acclimatization_procedure', models.TextField()),
                ('stocking_tips', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocking_guidelines', to='core.fishagegroup')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocking_guidelines', to='core.county')),
                ('farming_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocking_guidelines', to='core.farmingmethod')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocking_guidelines', to='core.fishspecies')),
            ],
            options={
                'indexes': [models.Index(fields=['fish_species', 'farming_method', 'age_group'], name='advisory_st_fish_sp_6ac989_idx')],
            },
        ),
    ]
