# Generated by Django 5.2.7 on 2026-04-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0005_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorysection',
            name='module_key',
            field=models.CharField(blank=True, help_text='Frontend module identifier (e.g., growth_prediction)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advisorysection',
            name='type',
            field=models.CharField(choices=[('guide', 'Guide'), ('module', 'Module')], default='guide', max_length=10),
        ),
    ]
