# Generated by Django 5.2.7 on 2026-05-27 21:41

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('species', models.CharField(max_length=50)),
                ('age_group', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('primary', 'Primary Feed'), ('booster', 'Growth Booster'), ('supplement', 'Supplement'), ('energy', 'Energy Feed')], default='primary', max_length=20)),
                ('protein_percent', models.FloatField()),
                ('fat_percent', models.FloatField(blank=True, null=True)),
                ('fiber_percent', models.FloatField(blank=True, null=True)),
                ('moisture_percent', models.FloatField(blank=True, null=True)),
                ('form', models.CharField(choices=[('pellet', 'Pellet'), ('crumble', 'Crumble'), ('powder', 'Powder'), ('live', 'Live Feed')], default='pellet', max_length=20)),
                ('cost_per_kg', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2026, 5, 27, 21, 40, 54, 670243, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='FeedingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('age_group', models.CharField(max_length=50)),
                ('meals_per_day', models.PositiveIntegerField(default=2)),
                ('feeding_interval_hours', models.FloatField(default=8)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='farm.pond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='feeding.feedingplan')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('plan', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='FeedingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField()),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed')], default='pending', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_grams', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feeding_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='feeding.feedingday')),
                ('feeds', models.ManyToManyField(blank=True, to='feeding.feed')),
            ],
            options={
                'ordering': ['scheduled_time'],
                'unique_together': {('feeding_day', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='FeedingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(default=1)),
                ('session_number', models.IntegerField(default=1)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('missed', 'Missed')], default='completed', max_length=20)),
                ('fed_at', models.DateTimeField(auto_now_add=True)),
                ('quantity_kg', models.FloatField(blank=True, null=True)),
                ('water_temperature', models.FloatField(blank=True, null=True)),
                ('oxygen', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feeds', models.ManyToManyField(blank=True, to='feeding.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_history', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='feeding.feedingplan')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeding.feedingsession')),
            ],
        ),
    ]
