# Generated by Django 5.2.7 on 2026-04-04 07:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedingrecord',
            options={'ordering': ['day']},
        ),
        migrations.AddField(
            model_name='feedingplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedingplan',
            name='current_day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='feedingplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedingrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedingrecord',
            name='day',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='feedingrecord',
            name='feeds_given',
            field=models.ManyToManyField(blank=True, to='feeding.feed'),
        ),
        migrations.AlterUniqueTogether(
            name='feedingrecord',
            unique_together={('plan', 'day')},
        ),
    ]
