# Generated by Django 5.2.7 on 2026-04-06 21:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0002_alter_feedingrecord_options_feedingplan_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingplan',
            name='current_day',
        ),
        migrations.AddField(
            model_name='feed',
            name='category',
            field=models.CharField(choices=[('protein', 'Protein'), ('energy', 'Energy'), ('vitamins', 'Vitamins'), ('minerals', 'Minerals'), (' other', 'Other')], default=' other', max_length=20),
        ),
        migrations.AddField(
            model_name='feedingplan',
            name='feeding_interval_hours',
            field=models.FloatField(default=8),
        ),
        migrations.AddField(
            model_name='feedingplan',
            name='meals_per_day',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='feedingplan',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedingplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='FeedingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='feeding.feedingplan')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('plan', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='FeedingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField()),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed')], default='pending', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_grams', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feeding_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='feeding.feedingday')),
                ('feeds', models.ManyToManyField(blank=True, to='feeding.feed')),
            ],
            options={
                'ordering': ['scheduled_time'],
                'unique_together': {('feeding_day', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='FeedingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('scheduled_time', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='feeding.feedingsession')),
            ],
        ),
        migrations.DeleteModel(
            name='FeedingRecord',
        ),
    ]
