# Generated by Django 5.2.7 on 2026-04-07 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0003_remove_feedingplan_current_day_feed_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='category',
        ),
        migrations.AddField(
            model_name='feed',
            name='cost_per_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 7, 14, 43, 15, 699415, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='feed',
            name='fat_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='fiber_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='form',
            field=models.CharField(choices=[('pellet', 'Pellet'), ('crumble', 'Crumble'), ('powder', 'Powder'), ('live', 'Live Feed')], default='pellet', max_length=20),
        ),
        migrations.AddField(
            model_name='feed',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='moisture_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary Feed'), ('booster', 'Growth Booster'), ('supplement', 'Supplement'), ('energy', 'Energy Feed')], default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
