# Generated by Django 5.2.7 on 2026-04-08 07:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0004_remove_feed_category_feed_cost_per_kg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 8, 7, 30, 55, 250914, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='completed', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('delay_minutes', models.IntegerField(blank=True, null=True)),
                ('feeds_used', models.JSONField(default=list)),
                ('quantity_kg', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('auto_generated', models.BooleanField(default=False, help_text='True if marked by system (missed detection)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feeding_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='feeding.feedingday')),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='feeding.feed')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='feeding.feedingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
