# Generated by Django 5.2.7 on 2026-04-18 15:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_remove_farmunit_farming_method_remove_farmunit_owner_and_more'),
        ('feeding', '0006_alter_feed_created_at_feedingnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingplan',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='farm.farm'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 18, 15, 42, 23, 651474, tzinfo=datetime.timezone.utc)),
        ),
    ]
