# Generated by Django 5.2.7 on 2026-04-20 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0007_feedingplan_farm_alter_feed_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 20, 8, 32, 50, 239645, tzinfo=datetime.timezone.utc)),
        ),
    ]
