# Generated by Django 5.2.7 on 2026-04-20 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0008_alter_feed_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 20, 11, 4, 41, 245464, tzinfo=datetime.timezone.utc)),
        ),
    ]
