# Generated by Django 5.2.7 on 2026-04-20 13:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_remove_pond_owner_pond_farm'),
        ('feeding', '0009_alter_feed_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingplan',
            name='farm',
        ),
        migrations.AddField(
            model_name='feedingplan',
            name='pond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='farm.pond'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 20, 13, 11, 54, 365815, tzinfo=datetime.timezone.utc)),
        ),
    ]
