# Generated by Django 5.2.7 on 2026-04-21 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0010_remove_feedingplan_farm_feedingplan_pond_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 21, 15, 11, 13, 407548, tzinfo=datetime.timezone.utc)),
        ),
    ]
