# Generated by Django 5.2.7 on 2026-04-26 07:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0011_alter_feed_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingnotification',
            name='session',
        ),
        migrations.RemoveField(
            model_name='feedingnotification',
            name='user',
        ),
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 26, 7, 8, 56, 458219, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='FeedingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fed_at', models.DateTimeField(auto_now_add=True)),
                ('quantity_kg', models.FloatField(blank=True, null=True)),
                ('water_temperature', models.FloatField(blank=True, null=True)),
                ('oxygen', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feeds', models.ManyToManyField(blank=True, to='feeding.feed')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='feeding.feedingplan')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeding.feedingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FeedingAlert',
        ),
        migrations.DeleteModel(
            name='FeedingNotification',
        ),
    ]
