# Generated by Django 5.2.7 on 2026-04-26 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0012_remove_feedingnotification_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 26, 8, 6, 53, 183445, tzinfo=datetime.timezone.utc)),
        ),
    ]
