# Generated by Django 5.2.7 on 2026-04-27 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0013_alter_feed_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 27, 11, 33, 22, 153592, tzinfo=datetime.timezone.utc)),
        ),
    ]
