# Generated by Django 5.2.7 on 2026-05-19 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0014_alter_feed_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedinghistory',
            name='actual_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedinghistory',
            name='day_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feedinghistory',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedinghistory',
            name='session_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feedinghistory',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('missed', 'Missed')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 19, 15, 14, 46, 349418, tzinfo=datetime.timezone.utc)),
        ),
    ]
