from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import ArrayField
from django.utils.text import slugify
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager
import uuid

# -------------------------------------------------------
# Custom User Manager
# -------------------------------------------------------

class CustomUserManager(BaseUserManager):
    """
    Custom manager for user model without a username field.
    Uses email as the unique identifier.
    """

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Users must have an email address")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError("Superuser must have is_staff=True")

        if extra_fields.get('is_superuser') is not True:
            raise ValueError("Superuser must have is_superuser=True")

        return self.create_user(email, password, **extra_fields)

# -------------------------------------------------------
# Custom User Model
# -------------------------------------------------------

class User(AbstractUser):
    """
    Custom User model that supports multiple roles.
    Username is auto-generated automatically.
    """

    USER_ROLES = [
        ('aspiring-farmer', 'Aspiring-farmer'),
        ('farmer', 'Farmer'),
        ('fisherman', 'Fisherman'),
        ('buyer', 'Buyer'),
        ('seller', 'Seller'),
    ]

    # Remove default username behavior
    username = None

    # Custom fields
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=20, unique=True)
    role = models.CharField(max_length=20, choices=USER_ROLES, default='farmer')
    is_verified = models.BooleanField(default=False)

    # Auto-generated username field (stored manually)
    autogenerated_username = models.CharField(max_length=100, unique=True, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["phone"]

    objects = CustomUserManager()

    def save(self, *args, **kwargs):
        # Auto-generate username if missing
        if not self.autogenerated_username:
            base = slugify(self.first_name or "user")
            unique_suffix = uuid.uuid4().hex[:6]
            self.autogenerated_username = f"{base}-{unique_suffix}"

        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.email} ({self.role})"

# -------------------------------------------------------
# Farmer Profile
# -------------------------------------------------------

class FarmerProfile(models.Model):

    FARMING_PLACES = [
        ('pond', 'Pond'),
        ('lake', 'Lake'),
        ('cage', 'Cage'),
        ('other', 'Other'),
    ]

    FISH_SPECIES = [
        ('tilapia', 'Tilapia'),
        ('nile perch', 'Nile Perch'),
        ('trout', 'Trout'),
        ('catfish', 'Catfish'),
        ('other', 'Other'),
    ]

    AGE_GROUPS = [
        ('fingerlings', 'Fingerlings'),
        ('juvenile', 'Juvenile'),
        ('matured fish', 'Matured Fish'),
    ]

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='farmer_profile'
    )

    # Location
    county = models.CharField(max_length=100)
    subcounty = models.CharField(max_length=100)

    # Farming Info
    place_of_farming = models.CharField(max_length=50, choices=FARMING_PLACES)
    fish_species = ArrayField(
        models.CharField(max_length=50, choices=FISH_SPECIES),
        default=list,
        blank=True
    )
    age_group = models.CharField(max_length=50, choices=AGE_GROUPS)

    date_registered = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.user.email} - {self.fish_species} ({self.place_of_farming})"


# -------------------------------------------------------
# 3️ Future Extendability
# -------------------------------------------------------
# You can later add similar profiles for other user types, like:

# class FishermanProfile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='fisherman_profile')
#     ...
#
# class BuyerProfile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='buyer_profile')
#     ...
#
# class SellerProfile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='seller_profile')
#     ...


