from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.contrib.auth.base_user import BaseUserManager

from django.utils import timezone
from django.utils.text import slugify
import uuid


# -------------------------------------------------------
# Custom User Manager
# -------------------------------------------------------

class CustomUserManager(BaseUserManager):
    """
    Custom manager for user model without a username field.
    Uses email as the unique identifier.
    """

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Users must have an email address")

        email = self.normalize_email(email)
        extra_fields.setdefault('is_active', True)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError("Superuser must have is_staff=True")

        if extra_fields.get('is_superuser') is not True:
            raise ValueError("Superuser must have is_superuser=True")

        return self.create_user(email, password, **extra_fields)


# -------------------------------------------------------
# Custom User Model
# -------------------------------------------------------

class User(AbstractUser):

    class Roles(models.TextChoices):
        ASPIRING_FARMER = "aspiring-farmer", "Aspiring Farmer"
        FARMER = "farmer", "Farmer"
        FISHERMAN = "fisherman", "Fisherman"
        BUYER = "buyer", "Buyer"
        SELLER = "seller", "Seller"

    # Remove default username
    username = None

    email = models.EmailField(unique=True)

    phone = models.CharField(
        max_length=20,
        unique=True,
        null=True,
        blank=True
    )

    role = models.CharField(
        max_length=20,
        choices=Roles.choices,
        default=Roles.FARMER,
        db_index=True
    )

    is_verified = models.BooleanField(default=False)

    autogenerated_username = models.CharField(
        max_length=100,
        unique=True,
        blank=True
    )

    date_created = models.DateTimeField(auto_now_add=True, null=True)
    date_updated = models.DateTimeField(auto_now=True, null=True)


    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["phone"]

    objects = CustomUserManager()

    def save(self, *args, **kwargs):
        if not self.autogenerated_username:
            base = slugify(self.first_name) if self.first_name else "user"
            unique_suffix = uuid.uuid4().hex[:6]
            self.autogenerated_username = f"{base}-{unique_suffix}"

        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.email} ({self.role})"

from core.models import (
    County,
    SubCounty,
    FishSpecies,
    FishAgeGroup,
    FarmingMethod,
)

# -------------------------------------------------------
# Farmer Profile Model
# -------------------------------------------------------

class FarmerProfile(models.Model):

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='farmer_profile'
    )

    county = models.ForeignKey(
        County,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='farmers'
    )

    subcounty = models.ForeignKey(
        SubCounty,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='farmers'
    )

    farming_method = models.ForeignKey(
        FarmingMethod,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='farmers'
    )

    fish_species = models.ManyToManyField(
        FishSpecies,
        blank=True,
        related_name='farmers'
    )

    age_group = models.ForeignKey(
        FishAgeGroup,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='farmers'
    )

    years_of_experience = models.PositiveIntegerField(
        null=True,
        blank=True
    )

    farm_size = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Farm size in acres or square meters"
    )

    date_registered = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-date_registered']

    def __str__(self):
        return f"{self.user.email} - Farmer Profile"

