# Generated by Django 5.2.7 on 2025-11-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=150, null=True)),
                ('farming_method', models.CharField(blank=True, max_length=50, null=True)),
                ('fish_species', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='task_steps/images/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='guidence.onboardingtask')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('task', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='FarmerTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farmerprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guidence.onboardingtask')),
            ],
            options={
                'unique_together': {('farmer', 'task')},
            },
        ),
        migrations.CreateModel(
            name='FarmerStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farmerprofile')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guidence.taskstep')),
            ],
            options={
                'unique_together': {('farmer', 'step')},
            },
        ),
    ]
