# Generated by Django 5.2.7 on 2026-02-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtask',
            name='fish_age_group',
            field=models.CharField(blank=True, choices=[('fingerlings', 'Fingerlings'), ('juvenile', 'Juvenile'), ('matured fish', 'Matured Fish')], max_length=20, null=True),
        ),
    ]
