# Generated by Django 5.2.7 on 2026-03-26 20:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('pond', 'Pond'), ('cage', 'Cage'), ('tank', 'Tank'), ('other', 'Other')], max_length=20)),
                ('size', models.FloatField(blank=True, help_text='Size in square meters', null=True)),
                ('depth', models.FloatField(blank=True, help_text='Depth in meters', null=True)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farming_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.farmingmethod')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_units', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255)),
                ('symptoms', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('action_taken', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('farm_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_incidents', to='farm.farmunit')),
            ],
        ),
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(max_length=100)),
                ('quantity', models.FloatField(help_text='Feed amount (kg)')),
                ('feeding_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('farm_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_logs', to='farm.farmunit')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_size', models.PositiveIntegerField(help_text='Number of fish sampled')),
                ('average_weight', models.FloatField(help_text='Average weight in grams')),
                ('recorded_at', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('farm_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_logs', to='farm.farmunit')),
            ],
        ),
        migrations.CreateModel(
            name='StockingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('average_weight', models.FloatField(blank=True, help_text='Initial average weight (grams)', null=True)),
                ('stocking_date', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, help_text='Supplier or hatchery', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fishagegroup')),
                ('farm_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockings', to='farm.farmunit')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fishspecies')),
            ],
        ),
        migrations.CreateModel(
            name='WaterQualityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='°C')),
                ('ph', models.FloatField(help_text='pH level')),
                ('dissolved_oxygen', models.FloatField(help_text='mg/L')),
                ('turbidity', models.FloatField(blank=True, null=True)),
                ('ammonia', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('farm_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='farm.farmunit')),
            ],
        ),
    ]
