# Generated by Django 5.2.7 on 2026-04-16 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmunit',
            name='farming_method',
        ),
        migrations.RemoveField(
            model_name='farmunit',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='growthlog',
            name='farm_unit',
        ),
        migrations.RemoveField(
            model_name='stockingrecord',
            name='farm_unit',
        ),
        migrations.RemoveField(
            model_name='waterqualitylog',
            name='farm_unit',
        ),
        migrations.RemoveField(
            model_name='feedinglog',
            name='farm_unit',
        ),
        migrations.RemoveField(
            model_name='stockingrecord',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='stockingrecord',
            name='fish_species',
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('depth', models.FloatField()),
                ('volume', models.FloatField(blank=True, null=True)),
                ('species', models.CharField(max_length=50)),
                ('stocking_date', models.DateField()),
                ('initial_count', models.IntegerField()),
                ('current_count', models.IntegerField()),
                ('initial_avg_weight', models.FloatField(help_text='Average weight per fish at stocking (grams)')),
                ('current_avg_weight', models.FloatField(help_text='Current average weight per fish (grams)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pond', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('ph', models.FloatField()),
                ('dissolved_oxygen', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_records', to='farm.pond')),
            ],
        ),
        migrations.DeleteModel(
            name='DiseaseIncident',
        ),
        migrations.DeleteModel(
            name='GrowthLog',
        ),
        migrations.DeleteModel(
            name='WaterQualityLog',
        ),
        migrations.DeleteModel(
            name='FarmUnit',
        ),
        migrations.DeleteModel(
            name='FeedingLog',
        ),
        migrations.DeleteModel(
            name='StockingRecord',
        ),
    ]
