# Generated by Django 5.2.7 on 2026-04-20 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_remove_farmunit_farming_method_remove_farmunit_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pond',
            name='owner',
        ),
        migrations.AddField(
            model_name='pond',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to='farm.farm'),
        ),
    ]
