# Generated by Django 5.2.7 on 2026-04-21 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_remove_pond_owner_pond_farm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pond',
            name='farm',
        ),
        migrations.AddField(
            model_name='pond',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pond', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
    ]
