# Generated by Django 5.2.7 on 2026-04-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_remove_pond_farm_pond_owner_delete_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='age_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
